### PR TITLE
Campus.il - Improving RTL for ORA problems

### PR DESCRIPTION
**Pull request by diegomillan**
## Background
In general this issue refers to making the ORA2 fully RTL enabled, improve the translations in Hebrew and Arabic,  and fixing  RTL alignments problems during all the series of steps. 

## Description
This PR improves RTL support marking strings for translations while fixing RTL alignments problems. Also, dates can be displayed in the correct locale format. 

## Sandbox:

LMS: https://cam29.opencraft.hosting

Studio: https://studio-cam29.opencraft.hosting

ORA2 Sample Unit in LMS: https://studio-cam29.opencraft.hosting/container/block-v1:edX+DemoX+Demo_Course+type@vertical+block@45c7cedb4bfe46f4a68c78787151cfb5#

ORA2 Sample Unit in Studio: https://studio-cam29.opencraft.hosting/container/block-v1:edX+DemoX+Demo_Course+type@vertical+block@45c7cedb4bfe46f4a68c78787151cfb5#

### Dates format
Supporting dates locale
captura de pantalla de 2018-03-26 10-41-46
dates_locale1

Before alignment patch for RTL langs
rtlbad
After alignment patch for RTL langs
rtlgood

Defaults translations
defen
After being marked and translated
deftrans

## Testing instructions
1. Set a RTL language for the platform.
2. Create a open response assessment.

## Related work
Find a PR supporting the same feature for ginkgo release [here](https://github.com/open-craft/edx-ora2/pull/1)

## Reviewers
- [ ] @nedbat  

cc @jagonzalr @mtyaka @tomaszgy @pomegranited

### CODE REVIEW

**Comment by tomaszgy** [comment]
@diegomillan, thanks for opening this PR :) Would you please have a look at the failed tests? Thanks!

**Comment by tomaszgy** [comment]
Also, I think you'll need to bump version of this repo [here](https://github.com/edx/edx-ora2/blob/2707d8acd19a379b8b02fb9b23f268cba20b382c/setup.py#L37).

**Comment by nedbat** [comment]
@diegomillan There's no need to tag me explicitly.  We have a process to see new pull requests.  The job of triaging them will move between people. Thanks.

**Comment by edx-webhook** [comment]
Thanks for the pull request, @diegomillan! I've created [OSPR-2342](https://openedx.atlassian.net/browse/OSPR-2342) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/edx-ora2/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by pomegranited** [comment]
@nedbat Since this PR marks more strings for translation, should we also include the updated `.po`/`.mo` files?

**Comment by pomegranited** [comment]
No worries @nedbat -- is there someone else we should be asking?  CC @efischer19

**Comment by efischer19** [comment]
If you have updates to the source files (`openassessment/locale/en/LC_MESSAGES/django.po` or `openassessment/locale/en/LC_MESSAGES/djangojs.po`), include them in your PR to be merged to master. Transifex is configured to watch those files (on master), and translated updates are pulled down by a weekly job which will be PR'd into the specific locale files ([like this](https://github.com/edx/edx-ora2/pull/1106))

**Comment by pomegranited** [comment]
@diegomillan Could you see @efischer19 's comment above, and include the translation updates in this PR? CC @tomaszgy

**Comment by mduboseedx** [comment]
@diegomillan Have you had a chance to work on this PR some more?

**Comment by diegomillan** [comment]
hi @tomaszgy @efischer19 @mduboseedx 

I just uploaded .po file. Now I will take a look at failing tests

**Comment by diegomillan** [comment]
Hi @tomaszgy @efischer19 @mduboseedx @pomegranited 

We have fixed 2 of 3 failing tests. Nevertheless,  we still have a problem when running `i18n_tool changed` with the following error message `Source translations are out-of-date! Please update them`. Since we are marking new strings for translation, could you help us to understand the issue here???

Thanks in advance

**Comment by mduboseedx** [comment]
@edx/testeng Do you what is going on with these tests?

**Comment by jmbowman** [comment]
I think you need to run "make extract_translations" to reflect the source changes in the *.po translation files, and then "make compile_translations" to update the optimized *.mo files used at runtime.

**Comment by mduboseedx** [comment]
@edx/learner-product Could you give this a quick look over? This changes the text alignment for ORAs and marks more strings for translations.

**Comment by tomaszgy** [comment]
@mduboseedx Thanks for a quick reply!

Would you also happen to know answer to this question:
> Do we need to include version bump for this repo in another commit? Then we could open another PR against edx-platform's master to update this requirement and hopefully get it cherry-picked on Hawthorn.

**Comment by mduboseedx** [comment]
@tomaszgy Yes, please open another PR for the version bump and we'll see if we can get it into Hawthorn once we complete our review. Thanks!

**Comment by pomegranited** [comment]
Thanks @diegomillan  and @mduboseedx ! Do you have an idea of when this PR might be reviewed/merged/tagged, so we can plan to update the version bump PR at the same time?

**Comment by mduboseedx** [comment]
@edx/learner-product @marcotuts Could you give this a quick check?

**Comment by mduboseedx** [comment]
And actually, this may be more of an Educator type of change. @edx/educator-product could you give this a quick check?

**Comment by pomegranited** [comment]
Thanks for your help here @mduboseedx !  Merging ASAP this is important to us because we need to get these translation changes into the Transifex Hawthorn branch, and so first, they need to go into Transifex master.

Is there anything we can do to make this review happen faster/easier?  Thanks!

**Comment by mduboseedx** [comment]
@edx/educator-all Could this be given a review? @sstack22 has looked it over and given it the go ahead

**Comment by diegomillan** [comment]
Hi @mduboseedx @sstack22,  do you know when you'll have a chance to review this PR? 
 
Thanks !!

cc @pomegranited

**Comment by mduboseedx** [comment]
@diegomillan I apologize for the delay. I was actually on vacation this past week and am just now catching up. Unfortunately, our Educator team will be unable to review any pull requests for a couple of weeks, but hopefully should be able to give a review later this month.

**Comment by bradenmacdonald** [comment]
@mduboseedx Since this one already has product review, I could give a second code review + merge, if that would help?

**Comment by mduboseedx** [comment]
@bradenmacdonald Yes, I think that would be ok. Thanks for your help!

**Comment by pomegranited** [comment]
@mduboseedx Since @bradenmacdonald  is now unable to merge PRs like this , we need your help getting this reviewed and merged.

The change itself should be non-controversial -- it improves the RTL and i18n support for ORA2.  It's getting quite urgent for us to merge this, since we need to update the translation strings in Transifex to prepare for a production release.

Is there anything we can do to help speed this along?

**Comment by pomegranited** [comment]
Scratch that @mduboseedx  -- there's still a number of changes required to this PR before it can be merged.  Will let you know when these changes are done.

**Comment by mduboseedx** [comment]
@pomegranited Thanks for letting me know. I reached out to our Product group as a heads up on this PR.

**Comment by itsjeyd** [comment]
@diegomillan The recent updates look good, thanks for those.

More changes might be needed here based on https://github.com/edx-olive-oc/edx-ora2/pull/2#pullrequestreview-169247415 (and the build is currently failing). But instead of updating both https://github.com/edx-olive-oc/edx-ora2/pull/2 and this PR simultaneously I'd suggest focusing on https://github.com/edx-olive-oc/edx-ora2/pull/2 for now, and apply any follow-up changes to this PR in a single iteration once https://github.com/edx-olive-oc/edx-ora2/pull/2 is ready for merge.

CC @pomegranited

**Comment by pomegranited** [comment]
@berkaybaykal  This PR hasn't been internally approved yet, and there are issues outstanding that need to be addressed before it's ready for edX review.

Could you please move this to Waiting on Author?

**Comment by edx-webhook** [comment]
Thanks for the pull request, @diegomillan! I've created [OSPR-3586](https://openedx.atlassian.net/browse/OSPR-3586) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by edx-webhook** [comment]
Thanks for the pull request, @diegomillan! I've created [OSPR-3592](https://openedx.atlassian.net/browse/OSPR-3592) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by feanil** [comment]
@pomegranited gonna close this for now, please re-open when you get back around to it.

**Comment by edx-webhook** [comment]
@diegomillan Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-ora2&entry.867055334=https://github.com/edx/edx-ora2/pull/1105&entry.1484655318=https://github.com/diegomillan&entry.752974735=2018-04-12+21:02&entry.1917517419=2019-06-05+20:21&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
