### PR TITLE
[BD-6] Remove six usage

### PR DESCRIPTION
**Pull request by morenol**
Remove usage of six using the python3 equivalent described in: https://six.readthedocs.io/

## Reviewers
- [ ] @awais786 
- [ ] @ericfab179

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @morenol! I've created [OSPR-4620](https://openedx.atlassian.net/browse/OSPR-4620) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by awais786** [comment]
@morenol please rebase.

**Comment by edx-webhook** [comment]
@morenol Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-ora2&entry.867055334=https://github.com/edx/edx-ora2/pull/1421&entry.1484655318=https://github.com/morenol&entry.752974735=2020-06-01+20:14&entry.1917517419=2020-06-15+16:20&entry.2133058324=No) so we can improve your experience in the future.

**Comment by morenol** [comment]
@awais786 done! tests are running and passing https://travis-ci.org/github/edx/edx-ora2/pull_requests but for some reason the check is not displayed here

**Comment by awais786** [comment]
> @awais786 done! tests are running and passing https://travis-ci.org/github/edx/edx-ora2/pull_requests but for some reason the check is not displayed here

@morenol I have asked devops to look into this. You this PR also showing same issue https://github.com/edx/jenkins-job-dsl/pull/1011

**Pull request merged**
