### PR TITLE
Add 'fix ajax contenttype' updated changes to minified js files

### PR DESCRIPTION
**Pull request by mushtaqak**
I missed to add changes to minified file in #729 

@waheedahmed @symbolist

### CODE REVIEW

**Comment by waheedahmed** [comment]
:+1:

**Comment by mushtaqak** [comment]
@cahrens can you review?

**Comment by cahrens** [comment]
I don't know how to review this, but if you followed whatever the process is for creating the minified files, then I'm sure it's fine.

**Comment by mushtaqak** [comment]
@symbolist Can you look at it?

**Comment by symbolist** [comment]
:+1:

**Pull request merged**
