### PR TITLE
Update requirements.

### PR DESCRIPTION
**Pull request by feanil**
This needs to be merged in close proximity to https://github.com/edx/edx-platform/pull/7842

### CODE REVIEW

**Comment by feanil** [comment]
@adampalay @e0d  Can you take a quick look here as well.

**Comment by feanil** [comment]
@wedaly Are there automated tests for the AI celery tasks? Or a writeup for how to manually test them once we get to stage?

**Comment by adampalay** [comment]
:+1: , but agree we should do some manual testing on this to be sure

**Comment by wedaly** [comment]
@feanil There are automated unit tests with a flag to run the celery tasks in-process, but not for the RabbitMQ / worker setup we use in prod.

**Comment by fredsmith** [comment]
:+1:

**Pull request merged**
