### PR TITLE
Changing wording of "waiting for peers" message.

### PR DESCRIPTION
**Pull request by cahrens**
TNL-4019

@andy-armstrong and @efischer19 please review

This is how it looks now:

image

### CODE REVIEW

**Comment by andy-armstrong** [comment]
As we discussed, I would like to also change the message at the top of the problem that is similarly confusing.

**Comment by cahrens** [comment]
@andy-armstrong I updated that second message as well.

FYI, @catong

**Comment by efischer19** [comment]
:+1: Looks good to me, I'd wait for @catong to give final approval on the exact wording but this is certainly better.

**Comment by catong** [comment]
Much better! :+1:

**Comment by andy-armstrong** [comment]
:+1: looks great!

**Pull request merged**
