### PR TITLE
Use improved Jasmine results plugin

### PR DESCRIPTION
**Pull request by andy-armstrong**
Use a Jasmine test results plugin that shows a clean summary of the tests that were run and shows those that failed. You can see an example (hopefully all passing) by clicking on the Travis details for this PR.

@cahrens @dianakhuang please review.

### CODE REVIEW

**Comment by andy-armstrong** [comment]
Note you have to scroll around to see the results. This is what they look like:

image

**Comment by andy-armstrong** [comment]
I should have mentioned that Alasdair added this plugin to the UI Toolkit which inspired me to add it to ORA as well.

**Comment by dianakhuang** [comment]
:+1:

**Comment by cahrens** [comment]
:+1:

**Pull request merged**
