### PR TITLE
fix: [SkillFacatory2035-1984] fix situation when users cannot check responses of other students in peer assessment if subsection due date has expired

### PR DESCRIPTION
**Pull request by YuriiBorovenskyi**
**Description:**
The PR fixes situation when users cannot check responses of other students in `peer assessment` if subsection due date has expired and updates version of `edx-ora2` plugin from 2.2.8 to 2.2.9.

**YouTrack:**
https://youtrack.raccoongang.com/issue/SkillFacatory2035-1984

**Related MR:** [skillfactory/edx-platform]()

**Merge checklist:**

* [ ] All reviewers approved
* [ ] CI build is green
* [ ] Demo status: OK
* [ ] All related documentation is updated
* [ ] DevOps notes added

**Post-Merge:**
- [ ] Create `rg-v.2.2.9-skillfactory` tag matching the new version number. (Will be made after merge)

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @YuriiBorovenskyi! I've created [OSPR-5866](https://openedx.atlassian.net/browse/OSPR-5866) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by YuriiBorovenskyi** [comment]
I apologize!
This PR was created by mistake.
And you shouldn't pay attention to it.
I close it.

**Comment by edx-webhook** [comment]
@YuriiBorovenskyi Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-ora2&entry.867055334=https://github.com/edx/edx-ora2/pull/1649&entry.1484655318=https://github.com/YuriiBorovenskyi&entry.752974735=2021-06-17+10:24&entry.1917517419=2021-06-17+10:56&entry.2133058324=No) so we can improve your experience in the future.

**Comment by natabene** [comment]
@YuriiBorovenskyi No problem, thanks for letting me know.

**Pull request closed without merging**
