### PR TITLE
TNL-7740: Update deprecated reference

### PR DESCRIPTION
**Pull request by giovannicimolin**
Signed-off-by: Giovanni Cimolin da Silva <giovannicimolin@gmail.com>

**TL;DR -** An update on edx-toggles broke ORA. This updates the import path and fixes it.

**What changed?**

- Import path of waffle switch

**Developer Checklist**
- [ ] Reviewed the [release process](./release_process.md)
- [ ] Translations up to date
- [ ] JS minified, SASS compiled
- [ ] Test suites passing on Jenkins
- [ ] Bumped version number in [setup.py](../setup.py) and [package.json](../package.json)

JIRA: [TNL-7740](https://openedx.atlassian.net/browse/TNL-7740)

FIY: @edx/masters-devs-gta

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @giovannicimolin! I've created [OSPR-5277](https://openedx.atlassian.net/browse/OSPR-5277) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by jansenk** [comment]
@jnlapierre mentioned this in standup and I was curious about context. Where are you seeing the related error? I ran through some ORA workflows on stage and saw no issues.

**Comment by giovannicimolin** [comment]
@jansenk I've seen this in the lastest version of the master devstack.
It's caused by https://github.com/edx/edx-toggles/releases/tag/1.2.0

**Comment by jansenk** [comment]
@giovannicimolin I don't really follow. What is the error? That release adds the __future__ module, why would we need to remove a reference to it?

**Comment by natabene** [comment]
@giovannicimolin Thank you for your contribution.

**Comment by giovannicimolin** [comment]
This issue is not happening on my devstack or in the sandbox I've set up. I think it was just a broken local package. Sorry for the noise, closing.

**Comment by edx-webhook** [comment]
@giovannicimolin Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-ora2&entry.867055334=https://github.com/edx/edx-ora2/pull/1547&entry.1484655318=https://github.com/giovannicimolin&entry.752974735=2020-12-02+14:49&entry.1917517419=2020-12-10+13:38&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
