### PR TITLE
Usability improvement for ORA

### PR DESCRIPTION
**Pull request by dmitry-viskov**
First part of usability improvements for ORA that were described here (Option A):

https://github.com/edx/edx-ora2/pull/970#issuecomment-275244482

>1.) Add new setting: Text Response. (default value: Required, other values: Optional, None)
2.) Add new setting: File Upload Response (default value: None, other values: Optional, Required)
3.) Rename existing setting "Allow File Uploads" --> "File Upload Types" and show this only if "File Upload Response is set to Optional / Required. (default value: PDF or Images, other values: Image Files, Custom File Types)
4.) Keep existing setting of "File Settings"

ora1

ora2

/cc @marcotuts @sstack22 @baldwin47

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @dmitry-viskov! I've created [OSPR-1720](https://openedx.atlassian.net/browse/OSPR-1720) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by sstack22** [comment]
Hi @dmitry-viskov - thank you! Does this PR (or https://github.com/edx/edx-ora2/pull/964) address the accessibility need for requiring descriptive text upon file upload? We will need that prior to releasing this feature.

**Comment by dmitry-viskov** [comment]
Hi @sstack22 . Current PR doesn't include descriptions for each uploading file. 
To add descriptions it is necessary to merge [this PR](https://github.com/edx/edx-ora2/pull/964) firstly.

As I understand we discussed [here](https://github.com/edx/edx-ora2/pull/970#issuecomment-276124655) that this development could be divided into two separate PR - (1) "Option A" and (2) "Required File Upload Descriptions". Since "Required File Upload Descriptions" development is blocked by [this PR](https://github.com/edx/edx-ora2/pull/964) I suggest to review (and probably merge) the current PR. Anyway "Required File Upload Descriptions" will be based on two features - this one and "Multiple file uploads support" (https://github.com/edx/edx-ora2/pull/964). So for "Required File Upload Descriptions" I'll create the third PR.

**Comment by gsong** [comment]
@sstack22 Do you have additional concerns about this PR, or can it progress to code review?

**Comment by sstack22** [comment]
@gsong  - apologies, forgot to update the status. This OSPR is in our backlog.

**Comment by dmitry-viskov** [comment]
Copied the current feature to this branch: https://github.com/edx/edx-ora2/pull/964

**Pull request closed without merging**
