### PR TITLE
Allow LaTeX previewing for multiple prompts

### PR DESCRIPTION
**Pull request by bdero**
Development for [openfun](https://github.com/openfun): This is a follow-up PR to #1017 and #1016. While implementing #1017, I missed implementing preview buttons for each prompt in the case where there is more than one prompt.

Please refer to the testing instructions in #1017!

**Screenshots**:

Before:
before screenshot

After:
after screenshot

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @bdero! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=1022&repo=edx%2Fedx-ora2"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

**Comment by edx-webhook** [comment]
Thanks for the pull request, @bdero! I've created [OSPR-1816](https://openedx.atlassian.net/browse/OSPR-1816) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/edx-ora2/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by bdero** [comment]
Hi @edx/doc, this PR along with https://github.com/edx/edx-ora2/pull/1017 makes a small modification to the interface for edx-ora2: When LaTeX is enabled, there are preview buttons available for all fields accepting LaTeX (not just the submission field).

Should I make a docs ticket for this change? I was able to find some documentation for ora2, but I couldn't seem to find any documentation referencing the interface, so I'm not sure if there is a doc at the moment.

**Comment by srpearce** [comment]
Hi @bdero — It looks like this PR will require a doc update, so it would be great if you could create a doc PR. Thanks!

We have the following end user documentation for ORA:

[Open Response Assessments](http://edx.readthedocs.io/projects/edx-partner-course-staff/en/latest/exercises_tools/open_response_assessments/index.html) (for edx.org course authors)

[Open Response Assessments](http://edx.readthedocs.io/projects/open-edx-building-and-running-a-course/en/latest/exercises_tools/open_response_assessments/index.html) (for Open edX course authors)

[Completing Essay Assignments](http://edx-guide-for-students.readthedocs.io/en/latest/SFD_ORA.html)  (for edx.org learners)

[Completing Essay Assignments](http://open-edx-learner-guide.readthedocs.io/en/latest/SFD_ORA.html)  (for Open edX learners)

**Comment by srpearce** [comment]
@bdero and @e-kolpakov : I just noticed the checklist above, and documentation is very much inside the scope of this PR—it's actually necessary. I was under the impression that you were going to create a DOC ticket, no? 

FYI, all of our course author and learner documentation is in the edx-documentation repo. You're welcome to submit a PR there.

**Comment by bdero** [comment]
@srpearce Apologies for the delay. I took a look and I was only able to find one mention of LaTeX in all the ORA2 documentation, which was for configuring the flag: https://edx.readthedocs.io/projects/edx-partner-course-staff/en/latest/exercises_tools/open_response_assessments/CreateORAAssignment.html#specify-the-response-type

It looks like as far as the end user experience is concerned, there is no documentation relating to the LaTeX previewing feature. I'm not sure it needs a whole section to explain it, but I'm thinking of adding a "Note" [here in the learner documentation|https://edx-guide-for-students.readthedocs.io/en/latest/SFD_ORA.html#submit-your-response] that basically says: "Some essay response problems accept LaTeX entry. In these cases, there will be a "Preview in LaTeX" button that can be used to generate a preview of the response before submission".

Do you think this would be the right change for me to make?

**Comment by srpearce** [comment]
@bdero That change to the learner docs sounds fine. I think it would fit best in the note under step 2 in the section you've mentioned.

**Comment by bdero** [comment]
@srpearce Alrighty, here's the [doc ticket](https://openedx.atlassian.net/browse/DOC-3718) which links to the PR!

**Pull request merged**
