### PR TITLE
Order assessment parts by criteria.

### PR DESCRIPTION
**Pull request by dianakhuang**
Fix for https://openedx.atlassian.net/browse/TNL-4352

### CODE REVIEW

**Comment by dianakhuang** [comment]
@efischer19 Here's the PR for the fix.

**Comment by efischer19** [comment]
👍 Seems simple enough to me, good catch

**Comment by dianakhuang** [comment]
@andy-armstrong could you be the second reviewer on this?

**Comment by andy-armstrong** [comment]
👍

**Pull request merged**
