### PR TITLE
Updates to labeling of the review inputs

### PR DESCRIPTION
**Pull request by staubina**
### Description

- Removed * from SR text
- Added Aria describedby and unique ID to the review questions in ORA2 to improve a11y.

### Sandbox
https://staubina-ora.sandbox.edx.org/courses/course-v1:edx+ORA203+course/courseware/a4dfec19cf9b4a6fb5b18be6ccd9cecc/4dbd99f691064633a9be0daadb805ce6/
- [x] Build a sandbox for your branch and add a link here

### Testing
- [x] Unit, integration, acceptance tests as appropriate

### Reviewers
If you've been tagged for review, please check your corresponding box once you've given the :+1:.
- [x] Code review: @cahrens 
- [x] Code review: @andy-armstrong 
- [x] Accessibility review: @cptvitamin 
FYI @sstack22 

### Post-review
- [x] Rebase and squash commits

### CODE REVIEW

**Comment by staubina** [comment]
@cptvitamin @sstack22 Please take a look when you have a moment.

**Comment by staubina** [comment]
@cptvitamin please review this PR when you get a chance.

FYI @sstack22

**Comment by staubina** [comment]
I am building a new Sandbox now.

**Comment by staubina** [comment]
@cptvitamin Sandbox updated and the link in the PR will also work.

**Comment by cptvitamin** [comment]
This looks great @staubina. My only question is: why is it only necessary for visually impaired users to know that those questions are required?  Shouldn't we make the word "Required" visible to all users?

**Comment by cptvitamin** [comment]
👍

**Pull request merged**
