### PR TITLE
Regisb/boto2to3

### PR DESCRIPTION
**Pull request by regisb**
**What changed?**

Boto is the old library that was used to interact with the AWS APIs, and
in particular the S3 API. It was replaced by boto3. We need to upgrade
boto to boto3 because boto makes it near impossible to customize the
connection settings.

It goes without saying that this should be tested with edX.org's own S3 settings to check whether the new configuration is compatible. In particular, it is possible that the default calling format has changed from "subdomain" to "ordinary".

**Developer Checklist**
- [x] Reviewed the [release process](./release_process.md)
- [x] Translations up to date
- [ ] ~~JS minified, SASS compiled~~
- [x] Test suites passing on Jenkins
- [x] Bumped version number in [setup.py](../setup.py) and [package.json](../package.json)

This is a follow up of a PR that has become stale: https://github.com/edx/edx-ora2/pull/1414 @ormsbee Do you think you could review this please? This is ready for review.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @regisb! I've created [OSPR-4912](https://openedx.atlassian.net/browse/OSPR-4912) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@regisb Thank you for your contribution. I will line this up for our review.

**Comment by nasthagiri** [comment]
@schenedx Can someone in your team take a look at this PR? Could this PR help bootstrap the maintenance effort the team will need to make to upgrade Boto?

**Comment by schenedx** [comment]
@mattcarter I think you are a better handler of this than me.

**Comment by mattcarter** [comment]
@schenedx I agree.  My team will review and see about getting this merged

**Comment by jansenk** [comment]
This was merged in https://github.com/edx/edx-ora2/pull/1504

**Comment by edx-webhook** [comment]
@regisb Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-ora2&entry.867055334=https://github.com/edx/edx-ora2/pull/1470&entry.1484655318=https://github.com/regisb&entry.752974735=2020-08-19+21:05&entry.1917517419=2020-09-28+13:26&entry.2133058324=No) so we can improve your experience in the future.

**Comment by regisb** [comment]
Thanks @jansenk!

**Pull request closed without merging**
