### PR TITLE
BOM-1569-part2

### PR DESCRIPTION
**Pull request by awais786**
https://openedx.atlassian.net/browse/BOM-1569

run make upgrade
Remove few constraints.
Bump the version.

### CODE REVIEW

**Comment by awais786** [comment]
@jmbowman this test is failing and I have checked on local with edx-submissions==3.1.1 it works fine.

This is the [3.1.2](https://github.com/edx/edx-submissions/commit/214b63f46c979120c8e5f82e040b9da165a2448e)
```
self = <openassessment.assessment.test.test_team.TestTeamApi testMethod=test_get_submission_to_assess>
    def test_get_submission_to_assess(self):
        # Given ungraded submissions to assess
        team_submission = self._create_test_submission_for_team()
    
        # When I ask the API for a submission
        submission_to_assess = teams_api.get_submission_to_assess(
            'mock-course',
            'mock-item',
            self.staff_user_id
        )
    
        # Then I recieve one to assess
>       self.assertEqual(team_submission, submission_to_assess)
E       AssertionError: {'sub[430 chars]er': '42', 'team_id': 'mock-team-id', 'course_[35 chars]': 1} != {'sub[430 chars]er': None, 'team_id': 'mock-team-id', 'course_[35 chars]': 1}
```

**Comment by awais786** [comment]
answer is coming None here.

**Comment by awais786** [comment]
@Andytr1 need your help in this failure.

**Comment by Andytr1** [comment]
Looking at it.

**Comment by Andytr1** [comment]
I created https://github.com/edx/edx-submissions/pull/115 and bumped its version. This will fix the issue.

**Pull request closed without merging**
