### PR TITLE
Proposal to display peer assessment results on the peer assessment step

### PR DESCRIPTION
**Pull request by dmitry-viskov**
Sometimes in some cases students may need to see how they were assessed by the other students (before the final score was obtained). It could be presented as the little block in the "peer assessment" view similar to "Peer Assessments for This Learner" tab in the staff window. If you are interested in this feature I may provide my solution (will be good to merge it into master :slightly_smiling_face:  ):

-------

-------

-------

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @dmitry-viskov! I've created [OSPR-2612](https://openedx.atlassian.net/browse/OSPR-2612) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by mduboseedx** [comment]
@marcotuts @shamck Could you talk a look at this proposal for ORA?

**Comment by marcotuts** [comment]
@dmitry-viskov  - Today we expose peer feedback in the final assessment area / step. We don't show this until the very end once all steps are completed. If we'd like to show peer responses / feedback earlier than the end we could look into an ORA option to "show feedback for each step", which would then let learners see their "Final Assessment" step with a message saying something to the effect of "You are seeing your feedback so far, but this does not reflect yoru final grade." 

This option would be a logic change / view rule change and doesn't add more UI to the ORA experience. Originally the pattern for the "dark UI" in ORA was intended for instructors only. 

Thoughts on this change / prospoal shift?

**Comment by mduboseedx** [comment]
@dmitry-viskov Have you had a chance to look over the proposal changes from @marcotuts? If so, are you still interested in this work?

Please let us know, otherwise we will close our your PR sometimes next week. Thanks!

**Comment by dmitry-viskov** [comment]
@marcotuts i think you understood me wrong. I suggest to display peer assessment result to the students. As i understand now this information is available only for the staff

**Comment by marcotuts** [comment]
Ah ok thanks @dmitry-viskov  this is helpful. 

My feedback would be that instead of adding the instructor facing dark UI for seeing peer responses, that if this setting is added, then you would be able as a student click the "Your Grade" section and see the peer responses in the rubric grading + feedback UI intended to be visible to learners. This would be available even before final grades are calculated. We may need to review language in this case to make it clear that it isn't the final grade but instead the peer responses only. 

Does that change make sense as described?

**Comment by natabene** [comment]
@dmitry-viskov I am curious if you are still interested in pursuing this. Please let me know if you have any questions, or need help.

**Comment by edx-webhook** [comment]
Thanks for the pull request, @dmitry-viskov! I've created [OSPR-3581](https://openedx.atlassian.net/browse/OSPR-3581) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by edx-webhook** [comment]
Thanks for the pull request, @dmitry-viskov! I've created [OSPR-3589](https://openedx.atlassian.net/browse/OSPR-3589) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@dmitry-viskov Checking if you are still interested in this or do you prefer to close this PR?

**Comment by feanil** [comment]
@dmitry-viskov since we haven't heard from you in a while, I'm closing this for now.  Please feel free to re-open it when you're able to come back to it.

**Comment by edx-webhook** [comment]
@dmitry-viskov Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-ora2&entry.867055334=https://github.com/edx/edx-ora2/pull/1125&entry.1484655318=https://github.com/dmitry-viskov&entry.752974735=2018-09-15+11:44&entry.1917517419=2019-06-11+19:41&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
