### PR TITLE
Update defaults.py

### PR DESCRIPTION
**Pull request by mshukurlu**
# -*- coding: utf-8 -*- line must be located on head of  page

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @mshukurlu! I've created [OSPR-3743](https://openedx.atlassian.net/browse/OSPR-3743) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://open.edx.org/wp-content/uploads/2019/01/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by natabene** [comment]
@mshukurlu Thank you for the contribution! When you have a chance, could you please send in a signed Contributor Agreement mentioned in the earlier comment? You only need to do this once and we can then review all your future code contributions. Thanks.

**Comment by natabene** [comment]
@mshukurlu Have you had a chance to sign the agreement and send to our legal team?

**Comment by mshukurlu** [comment]
@natabene  I am sorry . Due to my hard days, until today, I could not sign and send it to Legal time. But this great day I signed it and send to the team.

**Comment by natabene** [comment]
@mshukurlu Thank you for joining the Open edX community! We have added your user to our records and can now review your code going forward.

**Comment by natabene** [comment]
@ormsbee Can you give this a look?

**Comment by nedbat** [comment]
As a technical detail, the coding comment has to be either the first or second line of the file, so it worked as-is, but you are right: it's better as the first line.  Thanks.

**Comment by edx-webhook** [comment]
@mshukurlu 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-ora2&entry.867055334=https://github.com/edx/edx-ora2/pull/1253&entry.1484655318=https://github.com/mshukurlu&entry.752974735=2019-07-15+06:28&entry.1917517419=2019-09-23+15:30&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
