### PR TITLE
[BD-05][BB-3842] Fix issue with ORA pluggable submission editor

### PR DESCRIPTION
**Pull request by shimulch**
This PR fixes ORA pluggable submission editor issues in the staff area.

**JIRA tickets**: https://tasks.opencraft.com/browse/BB-3842

~~**Discussions**:~~
**Dependencies**: None

**Screenshots**: 
Staff area -

localhost_18000_courses_course-v1_edX+DemoX+Demo_Course_courseware_9fca584977d04885bc911ea76a9ef29e_07bc32474380492cb34f76e5f9d9a135_2_activate_block_id=block-v1%3AedX%2BDemoX%2BDemo_Course%2Btype%40vertical%2Bblock%40ecd8e99c8a2741588ba455

Instructor Dashboard -

localhost_18000_courses_course-v1_edX+DemoX+Demo_Course_instructor

Staff Grading with TinyMCE Response -

localhost_18000_courses_course-v1_edX+DemoX+Demo_Course_courseware_9fca584977d04885bc911ea76a9ef29e_07bc32474380492cb34f76e5f9d9a135_3_activate_block_id=block-v1%3AedX%2BDemoX%2BDemo_Course%2Btype%40vertical%2Bblock%40f7c31e00e7474dd2bc (1)

**Sandbox URL**: TBD

**Merge deadline**: ASAP

**Testing instructions**:

1. Pull this PR in your local devstack and install using `make install-local-ora`.
2. In your `lms.yml` set the feature flag `ENABLE_XBLOCK_VIEW_ENDPOINT` to `true`.
3. Restart LMS
2. Go to the studio and create a new ORA Block with Staff grading.
3. Publish the ORA Block.
4. Go to the ORA block in LMS.
5. Make a submission.
6. Click on the `Manage Individual Learners` button.
7. Enter the username you've used to do the submission.
8. From the result click `Learner's Response`.
9. Make sure that the submission text has been loaded as expected.
10. Click on the `Grade Available Responses` button.
11. Click on the `Staff Assessment` link.
12. Make sure that the submission text has been loaded correctly in staff grading.
13. Go to the instructor dashboard.
14. Visit the `ORA Responses` tab.
15. Click on the ORA block you have created.
16. Make sure that the submission texts are showing correctly.

**Author notes and concerns**:
N/A

**Reviewers**
- [ ] @giovannicimolin 
- [ ] edX reviewer[s] TBD

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @shimulch! I've created [BLENDED-775](https://openedx.atlassian.net/browse/BLENDED-775) to keep track of it in Jira.   More details are on the [BD-05](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1529970851/BD-05+ORA+v3+Usability+Moderation) project page.


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Review by giovannicimolin — APPROVED** [review]
:+1:

- [x] I tested this:
1. Checked out this branch on the devstack.
2. Set up two ORA blocks (one with text editor and one with TinyMCE) with staff responses.
3. Submitted responses.
4. Checked that the editors were properly rendered in the Staff areas (both on `Manage Individual Learners` and `Grade Available Responses` worked).
image
image
5. I've also tested that the editors worked on studio.
- [x] I read through the code
- [x] I checked for accessibility issues: Fixes content accessibility issue.
- [ ] ~~Includes documentation~~ NA

@shimulch Nice work! Thanks for the fast turnaround.

@jnlapierre @mattcarter This is ready for review.

**Comment by giovannicimolin** [comment]
Just for reference, screenshots using `master` :
image
image

This PR fixes this issue.

**Review by jnlapierre — APPROVED** [review]
LGTM

**Pull request merged**
