### PR TITLE
Usability improvement for ORA file uploads

### PR DESCRIPTION
**Pull request by baldwin47**
Implementation PRs:

* edx/edx-ora2#993

Related PRs:

* edx/edx-ora2#964

---

@jbarciauskas @marcotuts @sstack22 @scottrish - This is something that I would like to contribute in conjunction with the other ORA2 work we've sent over to you. Usability of this feature is important to us, so if there are other known issues that we could fix as a contribution, I'd be welcome to hearing what they are. 

Overview
There are serious usability issues with the Open Response Assessment file upload option. As it is currently built, the file upload seems to be meant as an optional, supplementary feature. A user must input text into the form input either way in order to submit the response. This requires crystal clear "process" instructions in every ORA prompt. Even then, we’ve found some users will ignore the process instructions in the prompt. 

We noticed this issue with an internal test (3/5 users with prior edx experience), where 5/5 users failed to submit a file. After that we ran a test on usertesting.com with the file upload ORA (5 users). 2 users were completely stuck and the other three ended up pasting their response from the word doc into the submission input. 2 of those three users also submitted a file, but the third did not. 

Some of our customers use files for their assessment records, so using file upload is a requirement in this case. 

Some of our use cases involve the file upload as the _primary_ method of submission. We would like to make an optional setting "Require File Upload" under the current Allow File Upload setting. 

We'd also like to make it possible to save and submit the ORA with _either_ a file or text in the input box, rather than always requiring text in the input box. This assumes that file upload and/or require file upload are selected. 

Here is what I would propose: 
1. Add a "Require File Upload" checkbox in the Allow File Upload section of ORA Settings
-  This should not be selectable if "None" (default) is selected for Allow File Upload
- If multiple files are specified, require each one if this box is checked
2. Allow the "Save your progress" button to be selectable if a file is uploaded to the ORA, even if there is no text in the submission form input
3. If "Require File Upload" is checked, allow the "Submit your response and move to the next step" button to be selectable if a file is uploaded to the ORA, even if there is no text in the submission form input

Existing Allow File Upload section:
allow file upload - settings

Unable to submit response as a file only:
screen shot 2017-01-25 at 2 07 43 pm

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @baldwin47! I've created [OSPR-1652](https://openedx.atlassian.net/browse/OSPR-1652) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation.     If you like, you can add yourself to the [AUTHORS](https://github.com/edx/edx-ora2/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by marcotuts** [comment]
Hi @baldwin47! Thanks for the early PR, the detailed visibility into rationale, user testing, etc. 

I wanted to provide quick / early feedback on this one since the scope of this is smaller and your team would potentially benefit from that quick turnaround.

Your proposal included the following capabilities / changes:
1.) New Require File Upload Checkbox
2.) Multiple File Upload Validation / Requirement
3.) Save your progress (for uploads)
4.) Optional Response (Text) Input

I wonder what you and your team would think about a slight adjustment to the proposed settings as noted in options A or B below:

**Option A: Text / File Upload Response Settings**
1.) Add new setting: Text Response. (default value: Required, other values: Optional, None)
2.) Add new setting: File Upload Response (default value: None, other values: Optional, Required) 
3.) Rename existing setting "Allow File Uploads" --> "File Upload Types" and show this only if "File Upload Response is set to Optional / Required. (default value: PDF or Images, other values: Image Files, Custom File Types)
4.) Keep existing setting of "File Settings" 

NOTE: The suggestion to split the current "Allow File Upload" into 2 settings might be overly complex, but the end result from an authoring standpoint is hopefully clearer in that authors could make their problems either purely upload, purely text, or a mix of the two. 

Edge Case: The approach described above would also need a validation case for ensuring that when File and Text are both optional, you can't submit your response until at least 1 has been added. That is, you can't submit an empty response...

**Option B: Rename, but Keep "Allow File Uploads" intact**
1.) Add new setting: Text Response. (default value: Required, other values: Optional, None)
2.) Keep existing setting Allow File Uploads with existing options
3.) Add setting "File Upload Response" shown only if "Allow File Uploads is "PDF or Image File, Image File, or Custom File Types": (default value: Optional, other value: Required)

**Comment by baldwin47** [comment]
@marcotuts I think Option A makes sense. I like the idea of allowing text response 'none.' I prefer option A because it sort of combines the current Allow File Upload and File Types. I agree, we would definitely want to make sure that setting both to optional wouldn't open up a loophole of being able to submit without a response. So assuming we agree on Option A as the preferred approach, we could start on this change?

**Comment by marcotuts** [comment]
Thanks for the reply @baldwin47. I'd love to give my colleagues a chance to chime in here if possible (cc'ed @sstack22, @katymyw), to make sure the suggested option A (which does have some field migrations!) is an ok direction.

**Comment by sstack22** [comment]
@baldwin47 - this is looking great! For accessibility purposes, if we remove the required text box, we would need a required field for learners to include descriptions of the files/images they are uploading. CC: @cptvitamin

**Comment by marcotuts** [comment]
To add some additional details to @sstack22's suggestion here, it looks like we would need to add a separate PR / feature to support a required 'description' field per uploaded file if we were to allow for the flexibility of optional or hidden text responses. 

Even without this PR proposal, the additional description fields could be merged in as a new ORA pull request, which would let us directly follow that up with Option A above. 

Any thoughts on that @baldwin47? Option A + Required File Upload Descriptions would be ready to start initial development.

**Comment by cptvitamin** [comment]
+1 for requiring user to include an image description for every image uploaded.  Ideally, this would happen in a modal dialog box, the same modal dialog box that is used to choose the image file. This would make the relationship between the image and the description explicit.  We should also include a brief set of instructions that clearly states why an image description is required (In ORA problems, there is no guarantee that the person who is reviewing your response can see the image.  You *must* provide a description that serves as a textual equivalent for the image, in the given context.)

**Comment by baldwin47** [comment]
Hi @marcotuts, thanks for the response. Your proposal sounds fine to me. I just have a couple clarifying questions. I can imagine the file description field displaying below each "choose file" button when file upload is enabled. Is that what you are envisioning? I have a little more trouble envisioning this for the select file screen as @cptvitamin describes - currently this is the browser or OS file selection screen. Let me know what you think and we will look to get these two PRs prioritized for active development.

**Comment by cptvitamin** [comment]
@baldwin47 my suggestion was to make the file selection happen in a custom modal dialog box that also included a text input for associating a text description for the image.  Currently, file selection happens in the main body of the course as a opposed to within a modal.

**Comment by marcotuts** [comment]
@baldwin47 - I can reply back with concept sketches later today to unblock this work. I think we can achieve the requirement of having required descriptive text per upload without needing to move away from the native file selector.

**Comment by dmitry-viskov** [comment]
@marcotuts could you please review my previous PR: https://github.com/edx/edx-ora2/pull/964 ?
Seems that development discussed here will be based on my previous PR

**Comment by baldwin47** [comment]
@marcotuts were you able to put together the concept sketches that you mentioned earlier in the week?

**Comment by marcotuts** [comment]
Thanks for commenting on this @baldwin47! I'll account for the changes based on your PR as well. Your original PR wast never reviewed / merged am I correct? 

STUDENT VIEWS
Current: Single Upload
image

Soon: Multiple Files (Current once OSPR-1646 merges)
image

Future: Single Upload (with description)
Similar to the multiple file case shown below

Future: Multiple Files (with description)
image


AUTHORING VIEWS:
(will add soon!)

**Comment by jbarciauskas** [comment]
Hey everyone, just checking in here - who owns the next steps? Is this ready for development or are there still points that need feedback?

**Comment by shellyu** [comment]
Excited about these changes! Several MITx and MITPE courses will benefit from this.

Question: will each file uploaded have a max file size of 5MB or will all files need to be under 5MB combined?

**Comment by marcotuts** [comment]
@shellyu  We discussed the file limit questions: limit each file, limit cumulative file size, etc in an earlier PR: https://github.com/edx/edx-ora2/pull/944#issuecomment-263308025 That being said perhaps we can continue that conversation on the currently open PR from @dmitry-viskov here: https://github.com/edx/edx-ora2/pull/964

**Comment by baldwin47** [comment]
@marcotuts any more concerns here? I commented in the file upload size PR. I think we're nearly ready to begin work on this. We have some courses starting in April where this will be needed.

**Comment by marcotuts** [comment]
@baldwin47 No immediate concerns here, though this is fairly complex, and has some dependencies with the multiple file PR. In particular one quesiton would be to explore whether this approach / change introduces any complex migrations to fields (ideally not, if we can avoid it.)  In addition, I don't know how many pull requests it will make sense to split this into, but if you have thoughts on that it would be helpful for us to track ocne those PRs are created. Additionally, either @katymyw or @sstack22 will also take a look to provide product feedback.

**Comment by sstack22** [comment]
@baldwin47 - let me know if there are any other open questions here, or if I can help out any. I believe the implementation is via  https://github.com/edx/edx-ora2/pull/964, so perhaps we should close this PR out? 

I think that all ORA PRs should be moving along at this point, but let me know if your team is blocked anywhere. Thank you very much for these contributions!

**Comment by dmitry-viskov** [comment]
@marcotuts @sstack22 
I've created the first PR with the usability improvement. Could somebody take a look?

// cc @baldwin47

**Comment by edx-webhook** [comment]
Hello @baldwin47: We are unable to continue with review of your submission at this time. Please see the associated JIRA ticket for more explanation.

**Pull request closed without merging**
