### PR TITLE
Campus.il - Adding mobile support

### PR DESCRIPTION
**Pull request by diegomillan**
### Description

This PR adds mobile support over ORA2, activating the "multi_device" decorator.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @diegomillan! I've created [OSPR-2729](https://openedx.atlassian.net/browse/OSPR-2729) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by e0d** [comment]
@staubina Are we concerned that this XBlock would start appearing in the mobile app without functioning correctly?

**Comment by e0d** [comment]
@pomegranited @diegomillan This PR is simple enough, but hard to merge confidently.  The code that "will need to be evaluated separately" is a reference to this same PR on a fork where the reviewer suggests that it be merged and then tested.  I don't see any feedback regarding that testing assuming it happened.

I'd like to make sure that this change will not break the existing edX mobile application in any way.

**Comment by pomegranited** [comment]
CC @itsjeyd  ^

**Comment by itsjeyd** [comment]
@e0d Thanks for the feedback! The testing that you're referring to hasn't happened yet. We'll likely [schedule it for the upcoming Campus sprint](https://github.com/edx-olive-oc/edx-ora2/pull/1#issuecomment-438964484).

Could you add the "Waiting on author" label to this PR in the meantime, to reflect its current status?

CC @ryangadams @pomegranited

**Comment by ryangadams** [comment]
Just updating this message to say that we've _finally_ got round to testing the ORA on a mobile device and have verified that it works when embedded in the app.

screenshot_2019-01-15-09-32-47-329_il gov campus

@e0d could you confirm if that is sufficient to give you confidence to merge?

**Comment by itsjeyd** [comment]
CC @natabene on the [comment](https://github.com/edx/edx-ora2/pull/1134#issuecomment-454327097) above. Could you please update the status of this? Not completely sure if it should go to "product review" or "engineering review", but since we didn't get an explicit thumbs-up from product yet, the former might be more appropriate.

**Comment by staubina** [comment]
@e0d I need to do some investigation of the status of ORA in the Mobile applications.  I believe it currently points users to the web.  So it should not suddenly show up in the app.  Although @marcotuts might be interested in adding testing this to our timeline once it is merged to the web side.  So that maybe we can stop redirecting in the app.

This is focused on the Mobile Web right @itsjeyd and/or @diegomillan ?

FYI @marcotuts

**Comment by ryangadams** [comment]
@staubina this is enabling ORA in the mobile app.

**Comment by staubina** [comment]
@ryangadams Thank you, I also just got caught up with the team.

I believe @marcotuts will want to do a little internal testing before moving forward.

@marcotuts Thoughts?

**Comment by staubina** [comment]
I will try and test locally over the next few days.  Is there a Sandbox up by chance? 

I can try to set one up if not.

**Comment by marcotuts** [comment]
We might need a mobile app build connected to a given sandbox so it may make sense for us to fully build an app / sandbox for this next testing. Thanks @ryangadams for this! 

@MirzaMubasharBaig  - Do we have what we need to be able to build a version of the platform using this edx-ora PR as the installed ORA2 version linked to a test mobile build?

**Comment by marcotuts** [comment]
@diegomillan - Would it be possible to get a sandbox link with this feature enabled, and an OAUTH_CLIENT_ID to make a mobile app build for us to test / review? Thanks!

**Comment by ryangadams** [comment]
@marcotuts we've done some additional internal testing here and have spotted some potential problems on iOS. It may be language related. I'll get those investigated and if necessary corrected. Meantime I'll see if I can organise a testing environment for you.

**Comment by natabene** [comment]
@ryangadams Thanks, please let us know once it is ready.

**Comment by edx-webhook** [comment]
Thanks for the pull request, @diegomillan! I've created [OSPR-3579](https://openedx.atlassian.net/browse/OSPR-3579) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by edx-webhook** [comment]
Thanks for the pull request, @diegomillan! I've created [OSPR-3588](https://openedx.atlassian.net/browse/OSPR-3588) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by feanil** [comment]
@ryangadams since we haven't heard back from you in a while, I'm closing this PR for now.  Please feel free to re-open it when you're able to come back to it.

**Comment by edx-webhook** [comment]
@diegomillan Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-ora2&entry.867055334=https://github.com/edx/edx-ora2/pull/1134&entry.1484655318=https://github.com/diegomillan&entry.752974735=2018-10-23+05:19&entry.1917517419=2019-06-11+19:22&entry.2133058324=No) so we can improve your experience in the future.

**Comment by roishillo** [comment]
Hi, Nice to meet you all - We are ready to reopen this - as we have the sandbox environment ready. I can invite you to the app in testflight, and you can check the solution.

**Comment by natabene** [comment]
@roishillo Thank you for letting us know. @marcotuts Do you want to review this again first, since it has been a while?

**Comment by roishillo** [comment]
Thank you Natali :) yes - it will be great to continue and do this merge. @marcotuts let me know if you need the credentials - and I can send you the invitation - I will also point you to the right course there. you may need to signup.

**Comment by roishillo** [comment]
Hi @natabene @marcotuts, let us know if you need any help there and if you want us to send you the credential to check it. We would like to upstream this change ASAP, as we want to upgrade our  platform to the new version. Let me know who can take it from here -

**Comment by natabene** [comment]
@roishillo Noted, we will take a look when we can.

**Comment by itsjeyd** [comment]
(Replaced by https://github.com/edx/edx-ora2/pull/1445.)

**Comment by natabene** [comment]
@itsjeyd Can this PR be closed?

**Comment by itsjeyd** [comment]
@natabene Yes, that should be fine.

CC @roishillo

**Comment by edx-webhook** [comment]
@diegomillan Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-ora2&entry.867055334=https://github.com/edx/edx-ora2/pull/1134&entry.1484655318=https://github.com/diegomillan&entry.752974735=2018-10-23+05:19&entry.1917517419=2020-07-27+02:50&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
