### PR TITLE
Rc/1.4.4

### PR DESCRIPTION
**Pull request by efischer19**
- [x] update translations
- [x] create a PR on edx-ora2 containing the version bump and translation updates. https://github.com/edx/edx-ora2/pull/1020
- [x] get a green Travis build on said PR https://travis-ci.org/edx/edx-ora2/builds/250880120
- [ ] merge to master
- [ ] green build on master
- [ ] create a release tag on GitHub https://github.com/edx/edx-ora2/releases
- [ ] manually inspect diff at https://github.com/edx/edx-ora2/compare/1.4.3...1.4.4, email contributors
- [ ] create PR to update `requirements/edx/github.txt` in `edx-platform`
- [ ] make sure that the ORA acceptance tests have run and passed against master
- [ ] get green build on the edx-platform PR, merge

### CODE REVIEW

**Comment by efischer19** [comment]
FYI @awaisdar001 @bdero @staubina @gsong - I'm cutting a new ORA release with changes you touched; it should be in edx-platform later today.

**Comment by bdero** [comment]
Thanks @efischer19!

There's another change in the pipe that's waiting for upstream review BTW if you'd prefer to rope it in (there's no deadline on our side with it, though): https://github.com/edx/edx-ora2/pull/1017#issuecomment-313376442

It extends the LaTeX preview button to work for all input fields that allow LaTeX content.

**Comment by efischer19** [comment]
Oh hey, that looks pretty cool! We're not in any rush to get this out either; I'll see if we can't get that reviewed and into this release.

**Comment by awaisdar001** [comment]
@efischer19  Should my change be present in  "Commits" and "Files Changed", I can not see it though?

**Comment by efischer19** [comment]
@awais786 This is a separate PR to update the translations and version number in code, your commits will be visible at https://github.com/edx/edx-ora2/compare/1.4.3...1.4.4 after I've merged this PR and created the new tag.

https://github.com/edx/edx-ora2/compare/1.4.3...master shows your commits, so they will be included in the new tag.

**Comment by awaisdar001** [comment]
@efischer19  Thank you :-)

**Comment by efischer19** [comment]
Alrighty, we're all rebased with the latest merges to master; release train is back on-track.

**Pull request merged**
