### PR TITLE
persisting ORA free text response in responseAggregator now

### PR DESCRIPTION
**Pull request by oolawo09**

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @oolawo09! I've created [OSPR-1687](https://openedx.atlassian.net/browse/OSPR-1687) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation.     If you like, you can add yourself to the [AUTHORS](https://github.com/edx/edx-ora2/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by gsong** [comment]
@oolawo09 Can you also provide some context of the use case for this change? Thank you.

Also, you'll want to check the corresponding test failure to make sure it's not caused by a change you've made. If so, please fix the test as well.

**Comment by nasthagiri** [comment]
@oolawo09 Thank you for your contribution.  My team plans to review this PR in our next sprint, week of March 27th.  By then, would you be able to:
1. Rebase your PR against the latest master - to see if the test failures are addressed.
2. If not addressed, fix the test failure resulting from the PR.
3. Add unit tests for your changes.
4. Update the description of this PR with a rationale for your submission/change.

Thanks!

**Comment by gsong** [comment]
@oolawo09 Can you please address @nasthagiri's [comment](#issuecomment-287555473) above?

**Comment by edx-webhook** [comment]
Hello @oolawo09: We are unable to continue with review of your submission at this time. Please see the associated JIRA ticket for more explanation.

**Pull request closed without merging**
