### PR TITLE
Update version to 1.1.4

### PR DESCRIPTION
**Pull request by mushtaqak**
Version update to 1.1.4

- [x] have @efischer19  update translations
- [x] create a PR on edx-ora2 containing the version bump and translation updates. See https://github.com/edx/edx-ora2/pull/856 as an example
- [x] get a green Travis build on PR
- [ ] merge to master
- [ ] green build on master
- [ ] create a release tag on GitHub https://github.com/edx/edx-ora2/releases
- [ ] manually inspect diff at https://github.com/edx/edx-ora2/compare/0.x.n-1...0.x.n, email contributors
- [ ] create PR to update `requirements/edx/github.txt` in `edx-platform`
- [ ] get PR branch version installed on sandbox, run a11y and acceptance tests for ora
- [ ] get green build on the edx-platform PR, merge
- [ ] manually test changes in RC once weekly edx-platform release is on stage

@efischer19 Review ?

### CODE REVIEW

**Comment by mushtaqak** [comment]
I will have to go through this process tomorrow https://openedx.atlassian.net/wiki/display/ENG/ORA2+Release+Process.

And would I need any translation updates for this release ?

**Comment by efischer19** [comment]
I'll get the translation updates made on this branch, I think it's been a while since we updated them. 👍 on your version bump, but wait until I can get the translation updates before merging.

Here's hoping for a green PR build for tomorrow morning!

**Comment by mushtaqak** [comment]
Sounds good :)

**Comment by efischer19** [comment]
I've spot-checked the translations, they seem to be good.

Feel free to carry on with the release process once this has a green build

**Comment by mushtaqak** [comment]
Travis green build on master passed https://travis-ci.org/edx/edx-ora2/builds/124667093

**Comment by mushtaqak** [comment]
Release tag made, here's the diff: https://github.com/edx/edx-ora2/compare/1.1.3...1.1.4

@efischer19 , @dianakhuang and I are the only ones with merged commits in this release.

**Comment by mushtaqak** [comment]
`edx-platform` PR: https://github.com/edx/edx-platform/pull/12209

**Comment by mushtaqak** [comment]
Created sandbox http://ora2release.sandbox.edx.org/ against edx-platform branch `mushtaq/ora2_release` and ran all acceptance tests on it [here](http://jenkins.edx.org:8080/view/ora2/job/ora2-acceptance-tests/859/console). Got the green build

**Comment by mushtaqak** [comment]
edx/edx-platform#12209 PR has merged to master, and new changes will be in prod when next release go live :)

**Pull request merged**
