### PR TITLE
Update course with latex enabled.

### PR DESCRIPTION
**Pull request by benpatterson**
Latex was not enabled on the imported course; however we have a test that expects it
to be enabled.

Also update various names to match the contents of the tar.

### CODE REVIEW

**Comment by benpatterson** [comment]
@symbolist @andy-armstrong @wedaly 

I believe there is still more Jenkins work after this, but we are close to getting the ora2 integration tests back online.

**Comment by benpatterson** [comment]
@fredsmith @clytwynec could I get a look on this ditty?

**Comment by wedaly** [comment]
:+1:

**Comment by clytwynec** [comment]
:+1:  Looks good to me.

**Pull request merged**
