### PR TITLE
Add new backend for swift

### PR DESCRIPTION
**Pull request by rouja**
Add new back-end in order to use Swift (http://docs.openstack.org/developer/swift/) to manage uploaded files.
To use this new back-end, you have to set two new parameters :
- ORA2_SWIFT_URL : endpoint url
- ORA2_SWIFT_KEY : Meta Temp-Url-Key which has to be configure before on Swift

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @rouja! I've created [OSPR-1432](https://openedx.atlassian.net/browse/OSPR-1432) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation.     If you like, you can add yourself to the [AUTHORS](https://github.com/edx/edx-ora2/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by gsong** [comment]
@rouja, thank you for your PR. We appreciate you taking the time to make the contribution.

Please submit a [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf) to us so we can review this pull request. We realize it's additional work for you, but we're hoping you would make future contributions as well.

**Comment by rouja** [comment]
Hi,
I already sent it to legal@edx.org few hours ago. Did you receive it ?

**Comment by gsong** [comment]
@rouja Legal will let us know once they've processed the signed agreement. In the meantime, please check on the [Travis failure](https://travis-ci.org/edx/edx-ora2/builds/159272666).

**Comment by shaunagm** [comment]
@rouja Sorry for the delay, your agreement has been processed and I'm moving this back to product review.

**Comment by sstack22** [comment]
@rouja - happy to review this PR. Can you please add a bit more context on the impact of this change?

**Comment by rouja** [comment]
Sorry for the delay, actually, we are working on a project which doesn't use AWS but an OpenStack plateform. The equivalent of S3 on that plateform is Swift. So, in order to use Swift natively instead of a "special compatible S3 mode", we decided to add the support of this backend in edx-ora2. I tried to reproduce exactly the same behaviour that the S3 backend.

This change shouldn't have impact because in order to use this new backend, you have to set the variable ORA2_FILEUPLOAD_BACKEND = 'swift' which is by default 's3'. 

So like i said, if you want to use this backend, you have to set : 
ORA2_FILEUPLOAD_BACKEND= 'swift'
and you have to add two new parameters : 
ORA2_SWIFT_URL= endpoint url
ORA2_SWIFT_KEY= Meta Temp-Url-Key which has to be configure before on Swift

Let me know if you need more details.

**Comment by sstack22** [comment]
@rouja - thanks for the added context! This is good to go from a product perspective. I've moved it into engineering review.

**Comment by mtyaka** [comment]
This looks very nice. It would be great if `ORA2_FILEUPLOAD_BACKEND` and `ORA2_SWIFT_*` parameters could be set via ansible variables in https://github.com/edx/configuration.

**Comment by jzoldak** [comment]
FYI the tools core team is investigating a recommendation for Swift backend testing in this current sprint.

**Comment by rouja** [comment]
Hi,

It's a good new. I will try to do the PR to add  the new parameters in the ansible playbook.

**Comment by gsong** [comment]
@jzoldak Any updates on this?

**Comment by jzoldak** [comment]
@rouja I've added some basic tests, and put them in [a PR to your master branch](../../../ObjectifLibre/edx-ora2/pull/1/files). 
Feel free to merge, cherry-pick, etc. Whatever is most expedient on your side.

These new tests verify the methods that you implemented. They cover 82% of the code (I didn't write tests that raise expected errors.)

We could also add more tests that verify the actual upload/download against a fake, like we do mocking out s3 with moto but instead mocking out the Swift Object Storage with [mimic](https://github.com/rackerlabs/mimic). I would **not** consider that a requirement however.

**Comment by cahrens** [comment]
@rouja If you add the unit tests that @jzoldak wrote to your PR, we can get this reviewed and merged. Thanks!

**Comment by cahrens** [comment]
Thanks for adding the tests @rouja. Please clean it up so that continuous integration is passing (and rebase on master if you haven't recently).

**Comment by rouja** [comment]
Hi,

I hope tests will pass. I do not know how to run the tests that jzoldak has added locally. Do you have a documentation about how to run the tests ?

thanks you

**Comment by cahrens** [comment]
Looks like tests ran and passed. We will finish up the review of this in our next sprint (which starts in 2 days). Thanks!

**Comment by cahrens** [comment]
👍

**Comment by cahrens** [comment]
@rouja thanks for the persistence! I have merged this PR to edx-ora2. For your purposes, do you need edx-platform updated to use this version of edx-ora2, or is it OK for us to wait until the next time we need an ORA change pulled into edx-platform?

**Comment by rouja** [comment]
Hi,

You can wait until the next time you need an ORA change pulled into edx-platform.

Thanks you

**Pull request merged**
