### PR TITLE
[BD-05] [TNL-7310] [BB-3388] Pluggable ORA Submission Editor - Base

### PR DESCRIPTION
**Pull request by shimulch**
This PR adds pluggable submission editor support for ORA.

In order to add multiple submission editor along with pluggability following flow has been implemented -

1. ORA gets available editor configurations from ``editor_config.py`` where it's defined as -
```python
AVAILABLE_EDITORS = {
    'text': {  # key is the identification for the editor
        'display': 'Simple Text Editor',  # displays name in studio settings selectbox
        'js': ['/static/js/openassessment-editor-textarea.js'],  # this JS file tells ORA how this editor behaves 
        'css': []  # this CSS files will be included
    },
}
```
2. This ``AVAILABLE_EDITORS`` can be overridden by the ``ORA_AVAILABLE_EDITORS`` settings.
3. ORA uses the ``ResponseEditorLoader`` to load the selected editor. Selected editor and Available editor configuration are passed via JS context.
4. ``ResponseEditorLoader`` uses ``RequireJS`` to load JS files from the editor config.
4. The file that tells how a ``Editor`` behaves should have the following statucture -
```javascript
(function (define) {
  define(['additional js for this editor to work'], () => {
    class Editor {
      load(elements) {} // loads the editor

      setOnChangeListener(handler) {} // binds handler to editor's on change
      
      response(texts) {} // sets editor value if texts are present else returns existing values
    }  

    // return a function, to be able to create a new instance every time. 
    // otherwise, it can collide with other ORA block in same subsection.
    return function () {
      return new Editor();
    };
  });

// Studio has define directly on the window, LMS has RequireJS.
}).call(window, window.define || window.RequireJS.define);

```

**JIRA tickets**: 
- https://openedx.atlassian.net/browse/TNL-7310
- https://tasks.opencraft.com/browse/BB-3388

~~**Discussions**:~~

**Dependencies**: None

**Screenshots**: 
pluggable-ora-submission-editor

**Sandbox URL**: https://bb3388.sandbox.opencraft.hosting/

**Merge deadline**: None

**Testing instructions**:

1. Clone this PR on your local devstack. Install using ``make install-local-ora``. 
2. Create an ORA block. On the settings tab check that ``Response Editor`` Dropdown is available.
3. Check that the ORA block working fine as before this implementation.

**Author notes and concerns**:

1. This implementation utilizes the availability of ``RequireJS`` on both LMS and Studio. 

**Reviewers**
- [ ] @viadanna
- [ ] @xitij2000
- [ ] @giovannicimolin 
- [ ] edX reviewer[s] TBD

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @shimulch! I've created [BLENDED-726](https://openedx.atlassian.net/browse/BLENDED-726) to keep track of it in Jira.   More details are on the [BD-05](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1529970851/BD-05+ORA+v3+Usability+Moderation) project page.


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by viadanna** [comment]
Good to go 👍

Just make sure to check the conflicts ;)

- [x] I tested this on my devstack.
- [x] I read through the code.

**Review by viadanna — APPROVED** [review]

**Comment by giovannicimolin** [comment]
@jnlapierre @mattcarter This is ready for review.

**Review by jnlapierre — APPROVED** [review]
LGTM please resolve the merge conflict.

**Comment by shimulch** [comment]
@jnlapierre Thanks a lot for the review. I've rebased & squashed my commits. cc @giovannicimolin

**Comment by shimulch** [comment]
Closing this as the PR has been merged as part of https://github.com/edx/edx-ora2/pull/1576.

**Pull request closed without merging**
