### PR TITLE
Ahsan/tnl 68 list structure unnecessary

### PR DESCRIPTION
**Pull request by ahsan-ul-haq**
List structure was used to structure the pages of ora2 which
results lot of unnecessary verbosity

TNL-68

### CODE REVIEW

**Comment by ahsan-ul-haq** [comment]
@symbolist could you please review this one

**Comment by symbolist** [comment]
Please hold off on this one now.

**Comment by ahsan-ul-haq** [comment]
@symbolist @cptvitamin could you please review this and let me know if it is good to merge

**Comment by ahsan-ul-haq** [comment]
@cptvitamin kindly review this

**Comment by symbolist** [comment]
@ahsan-ul-haq The changes look good to me. Have you also verified that this does not effect any styling? Also the commits would need squashing before merge.

**Pull request closed without merging**
