### PR TITLE
Re-display assessment tables after tabbing away

### LINKED ISSUE #1240: Tables don

### PR DESCRIPTION
**Pull request by bryanlandia**
Adds code to show the tables if returning the table view if the data has been already been rendered.  Tables were only re-displaying when returning from the detailed view of an assessment or from the staff grading view.

Fixes #1240

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @bryanlandia! I've created [OSPR-3611](https://openedx.atlassian.net/browse/OSPR-3611) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@bryanlandia Thank you for your contribution. Can you look into the failing Travis test before we start reviewing this?

**Comment by OmarIthawi** [comment]
@natabene I don't think the failed tests has anything to do with the pull request. The same issue also appears in this previous pull request by edX Translation Bot https://github.com/edx/edx-ora2/pull/1244

From previous experiences, fixing an unrelated error could be a rabbit hole.

Could we please mark this as ready for review? If it's good to go, I think it's worth the investment to fix the unrelated error, otherwise I think it's fair to just close this pull request and not spend too much time on it.

Thank you!

cc: @bryanlandia

**Comment by natabene** [comment]
@marcotuts Do you need to review this before it goes to engineering review?

**Comment by marcotuts** [comment]
this looks good to move to engineering review to me. thanks for the context on this and the linked ticket @bryanlandia !

**Comment by natabene** [comment]
@ormsbee Is this something you could review?

**Comment by bryanlandia** [comment]
@ormsbee @natabene hoping this could get a review soonish.  The conflict is unavoidable on the minified JS as other changes are made, so that shouldn't be a blocker.  I can rebase and regenerate the min.js once the code overall is approved.

**Comment by natabene** [comment]
@ormsbee Whenever you have a chance, please take a look.

**Comment by natabene** [comment]
@bryanlandia We have not heard from you in a while, so I am closing. If you decide to implement requested changes, please feel free to re-open this PR.

**Comment by edx-webhook** [comment]
@bryanlandia Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-ora2&entry.867055334=https://github.com/edx/edx-ora2/pull/1241&entry.1484655318=https://github.com/bryanlandia&entry.752974735=2019-05-25+00:47&entry.1917517419=2019-12-30+16:27&entry.2133058324=No) so we can improve your experience in the future.

**Comment by OmarIthawi** [comment]
Hi @natabene. Thanks for ping. I think I can do the changes David asked for. Please re-open the PR so I can push force the branch.

**Pull request closed without merging**
