### PR TITLE
Added LaTeX preview feature to all comment/feedback fields

### PR DESCRIPTION
**Pull request by bdero**
ORA2 already offers LaTeX previewing when LaTeX is enabled for submissions, but the peer assessment and self assessment sections also allow for inputting LaTeX, even though there are no preview buttons for these fields.

This change adds a LaTeX preview button to each of these fields that are currently missing it.

**Screenshot:**

screenshot

**Testing setup:**

1. Clone this repository into the `/edx/app/src` directory, checkout the branch for this PR, and install the xblock like so:
   ```
   pip install -e file:///edx/src/edx-ora2/#egg=ora2==localdev
   ```
1. Go to the `Advanced Settings` of a course in Studio and add `"ora2"` to the *Advanced Module List*
1. Add an "Open Response Assessment" problem to a new Unit
1. Select "Edit" on the new ORA problem to open the settings modal
1. Change "Allow LaTeX Responses" to `True`, and click *Save* to close the settings dialog
1. Publish the Unit

**Testing instructions:**

1. Logged in with two different users (I'll refer to them as *User A* and *User B*), navigate to the new ORA2 problem in the LMS
1. *User A*: Type some LaTeX markup into the submission field, for example:
   ```latex
   \begin{align}
   u_{n}&amp;=-3+\frac{3n}{2}\\
   &amp;=\frac{3n-6}{2}
   \end{align}
   ```
1. *User A*: Select "Preview in LaTeX" to verify that it (still) works as expected
1. *User A*: Submit the response and then complete the "Learn to Assess Responses" section
1. *User B*: Submit a response, and then complete the "Learn to Assess Responses" section - you will be prompted to assess *User A*'s submission in the "Assess Peers" section
1. *User B*: Observe that there are "Preview in LaTeX" buttons below each of the fields
1. *User B*: Type some LaTeX markup into each of the fields and verify that the "Preview in LaTeX" feature works as expected

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @bdero! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fedx-ora2&number=1017"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

**Comment by edx-webhook** [comment]
Thanks for the pull request, @bdero! I've created [OSPR-1801](https://openedx.atlassian.net/browse/OSPR-1801) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/edx-ora2/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by jul** [comment]
We are testing here too (fun-mooc). Tests are conclusive so far: it works as advertised.

**Comment by sstack22** [comment]
@bdero - this looks great! Just want to confirm - the preview button only appears when a comment is written in latex? That is my only concern.

**Comment by bdero** [comment]
@sstack22 Thanks, and yup, all of the preview buttons/areas will only show up if the latex option is [enabled for the xblock](https://github.com/edx/edx-ora2/pull/1017/files#diff-00e5cfe0c5d3ec07fd858d46534b52edR3).

**Comment by sstack22** [comment]
👍  from product review.

**Pull request merged**
