### PR TITLE
Upgrade boto to boto3

### PR DESCRIPTION
**Pull request by regisb**
**What changed?**

Boto is the old library that was used to interact with the AWS APIs, and
in particular the S3 API. It was replaced by boto3. We need to upgrade
boto to boto3 because boto makes it near impossible to customize the
connection settings.

It goes without saying that this should be tested with edX.org's own S3 settings to check whether the new configuration is compatible. In particular, it is possible that the default calling format has changed from "subdomain" to "ordinary".

**Developer Checklist**
- [x] Reviewed the [release process](./release_process.md)
- [x] Translations up to date
- [ ] ~~JS minified, SASS compiled~~
- [x] Test suites passing on Jenkins
- [x] Bumped version number in [setup.py](../setup.py) and [package.json](../package.json)

FIY: @edx/masters-devs-gta

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @regisb! I've created [OSPR-4592](https://openedx.atlassian.net/browse/OSPR-4592) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@regisb Thank you for your contribution. Is this ready for our review?

**Comment by regisb** [comment]
@natabene yes, absolutely :)

**Comment by natabene** [comment]
@ormsbee Is this something you can review? If not, would you recommend anyone else?

**Comment by regisb** [comment]
ping @ormsbee?

**Comment by regisb** [comment]
This PR needs to be rebased, but I need to preserve the branch name for building Docker images. Thus closing this and re-opening with a different branch name.

**Comment by edx-webhook** [comment]
@regisb Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-ora2&entry.867055334=https://github.com/edx/edx-ora2/pull/1414&entry.1484655318=https://github.com/regisb&entry.752974735=2020-05-27+12:26&entry.1917517419=2020-08-19+21:04&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
