### PR TITLE
Unnecessary tabpanel to navigate activity steps

### PR DESCRIPTION
**Pull request by ahsan-ul-haq**
unnecessary tabpanel to navigate activity steps was used which was noth currently functioning
properly. It is currently considered reduntant so removed.

TNL-69

### CODE REVIEW

**Comment by ahsan-ul-haq** [comment]
@cptvitamin could you please review whether this is how you want it to be?

**Comment by ahsan-ul-haq** [comment]
@symbolist Could you please review it

**Comment by symbolist** [comment]
If this is what is required. :+1:

**Comment by cptvitamin** [comment]
Thank @ahsan-ul-haq.  This is exactly what needed to be done.  This navigation for screen reader users is unnecessary as the page has sufficient navigational aids already and its inclusion was actually confusing for keyboard only users.  Thanks for removing it :+1:   please merge.

**Pull request merged**
