### PR TITLE
Fixed student can't view their submission after recieving grades.

### PR DESCRIPTION
**Pull request by waheedahmed**
[TNL-2000] (https://openedx.atlassian.net/browse/TNL-2000)

After student receives grade in ORA, they can no longer view their submission.

Fixed and test added.

### CODE REVIEW

**Comment by waheedahmed** [comment]
@symbolist @adampalay @muzaffaryousaf Please review this.

**Comment by symbolist** [comment]
Oh, I can't believe how I missed this! Thanks for fixing it. :+1:

**Comment by muzaffaryousaf** [comment]
lgtm :+1:

**Comment by adampalay** [comment]
@waheedahmed make sure you submit a PR against edx-platform to update the ora2 release version

**Pull request merged**
