### PR TITLE
quick 'n dirty fix

### PR DESCRIPTION
**Pull request by efischer19**
@cahrens This ought to get you working again while we decide what the proper fix is for https://openedx.atlassian.net/browse/TNL-3865. @dianakhuang can you be the second set of thumbs?

Also I guess I accidentally fixed some non-empty lines? I can revert those if you want, but it seems like a "better than I found it" situation so if you don't mind I'll just leave it.

### CODE REVIEW

**Comment by dianakhuang** [comment]
:+1: Though I definitely think we'll need to do something smarter about this later.

**Comment by efischer19** [comment]
Agreed, this smells pretty funky to me. Definitely needs more attention in the future.

**Comment by efischer19** [comment]
Argh, buttons! Agreed @dianakhuang, this "fix" smells pretty funky, we'll need to be smarter for a long-term solution

**Comment by efischer19** [comment]
@dianakhuang I had to make a change to the commit - still the same idea, but now with less `KeyError` after running tests locally.

**Comment by dianakhuang** [comment]
:+1:

**Comment by efischer19** [comment]
Superseded by https://github.com/edx/edx-ora2/pull/806

**Pull request closed without merging**
