### PR TITLE
Ignore warnings bubbling up in tests

### PR DESCRIPTION
**Pull request by benpatterson**

### CODE REVIEW

**Comment by benpatterson** [comment]
@jzoldak

**Comment by jzoldak** [comment]
@benpatterson code LGTM.
[The build](https://travis-ci.org/edx/edx-ora2/builds/64474801) failed, so I kicked off another one. I suspect it's unrelated to your change but instead due to a flaky test?

**Comment by benpatterson** [comment]
@jzoldak it wasn't related to my changes; it appeared to be a pip caching issue. I made a change to get our pip installs to be in a known state with that last commit. Build passes now :)

**Comment by jzoldak** [comment]
:+1:

**Pull request merged**
