### PR TITLE
Make checkboxes accessible.

### PR DESCRIPTION
**Pull request by cahrens**
TNL-3999

This changes the checkboxes in Studio ORA problem settings to use the native control instead of hiding it and showing font awesome icons. Using the native control allows keyboard accessibility to work (can tab into the control and toggle it).

image

@efischer19 and @andy-armstrong please review

### CODE REVIEW

**Comment by cahrens** [comment]
FYI @cptvitamin this will fix the checkboxes in the Studio ORA settings. I've already updated my sandbox with the change for testing purposes.

**Comment by andy-armstrong** [comment]
@talbs Do you remember why ORA didn't use the native controls originally? Are you comfortable with switching over?

**Comment by cahrens** [comment]
@talbs has no idea, and he helped me with the CSS removal.

**Comment by efischer19** [comment]
:+1: from me

**Comment by andy-armstrong** [comment]
FYI here's the PR where Grady introduced this code. I don't see any comments as to why he did it, or review feedback on those lines:

https://github.com/edx/edx-ora2/pull/445

The only thing I could think of is that web fonts will scale up with font size, but that seems like a minor benefit compared to the loss of accessibility.

**Comment by andy-armstrong** [comment]
:+1: given that nobody remembers why we did this. :-)

**Pull request merged**
