### PR TITLE
Move focus within staff panels.

### PR DESCRIPTION
**Pull request by cahrens**
TNL-3932

When one of the staff area buttons is clicked, focus needs to move into the panel, to the first focusable component. This is the close button (which was OK'd by @cptvitamin as the right thing to do).

Sandbox: https://cahrens.sandbox.edx.org

@efischer19 and @andy-armstrong please review

### CODE REVIEW

**Comment by efischer19** [comment]
:+1: Looks good to me

**Comment by andy-armstrong** [comment]
:+1: Looks great. As we just discussed, it would be good to decide where the focus should go when you close the panel too.

**Comment by cahrens** [comment]
Excellent point, @andy-armstrong. I have updated the PR (and sandbox) to have focus go back to the "tab" on close. Sorry, but I squashed the commit at the same time.

**Comment by cahrens** [comment]
@efischer19 you should re-review as well.

**Comment by andy-armstrong** [comment]
:+1:

**Comment by efischer19** [comment]
:+1: Tested on sandbox, closing behavior looks good as well.

**Pull request merged**
