### PR TITLE
Use lazy translation to avoid import issues

### PR DESCRIPTION
**Pull request by efischer19**
@robrap, I believe this will fix the issues you pinged me about. Can you review when you get a chance?

If you need this to go out soon I can do an ORA release after we merge this in

### CODE REVIEW

**Comment by efischer19** [comment]
👍 sounds good. I'll merge once tests pass, but won't make a new ORA release just for this.

**Comment by robrap** [comment]
Understood.  Thanks.

**Comment by doctoryes** [comment]
@efischer19 FYI - the issue that was fixed by this PR is causing a stack trace during LMS (and other) testing on my devstack. Here's the full error:
```
WARNING:xblock.plugin:Unable to load XBlock 'openassessment'
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/xblock/plugin.py", line 146, in load_classes
    yield (class_.name, cls._load_class_entry_point(class_))
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/xblock/plugin.py", line 75, in _load_class_entry_point
    class_ = entry_point.load()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2296, in load
    return self.resolve()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2302, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/openassessment/xblock/openassessmentblock.py", line 30, in <module>
    from openassessment.xblock.studio_mixin import StudioMixin
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/openassessment/xblock/studio_mixin.py", line 31, in <module>
    class StudioMixin(object):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/openassessment/xblock/studio_mixin.py", line 48, in StudioMixin
    "required": _("Required"),
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 84, in ugettext
    return _trans.ugettext(message)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 330, in ugettext
    return do_translate(message, 'ugettext')
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 307, in do_translate
    _default = _default or translation(settings.LANGUAGE_CODE)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 209, in translation
    _translations[language] = DjangoTranslation(language)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 118, in __init__
    self._add_installed_apps_translations()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 159, in _add_installed_apps_translations
    "The translation infrastructure cannot be initialized before the "
AppRegistryNotReady: The translation infrastructure cannot be initialized before the apps registry is ready. Check that you don't make non-lazy gettext calls at import time.
```
Any idea when the next ORA2 release containing this fix will happen?

**Comment by efischer19** [comment]
@doctoryes I've been noticing that as well - I can just go ahead and push out a release tomorrow, it won't take too much effort.

I think there's going to be a similar release made for the similar "is not from an app in INSTALLED_APPS" warnings, but that fix is more non-trivial than this.

**Comment by doctoryes** [comment]
Thanks. In Django 1.9, the code is not allowed to import models before the "application was loaded". The warnings are likely caused by that condition and will need a deeper fix.

**Pull request merged**
