### PR TITLE
Use docker

### PR DESCRIPTION
**Pull request by benpatterson**
Will run this on Travis to see if it help Dave's PR

### CODE REVIEW

**Comment by benpatterson** [comment]
@singingwolfboy I took your PR and made docker-friendly changes to it. What do you think?

**Comment by singingwolfboy** [comment]
This looks awesome! :+1:

**Comment by benpatterson** [comment]
FYI @jzoldak @wedaly

**Comment by benpatterson** [comment]
Just in my own development, it easily sped up travis builds (moreso build *assignment*) by an order of magnitude.

**Pull request merged**
