### PR TITLE
ORA, now with icons!

### PR DESCRIPTION
**Pull request by cahrens**
## [TNL-3741](https://openedx.atlassian.net/browse/TNL-3741)

When the font awesome upgrade happened (see #6515), ora2 was not updated.

### Sandbox
- [x] http://fa.sandbox.edx.org/

### Testing
- [x] Unit, integration, acceptance tests as appropriate

### Reviewers
If you've been tagged for review, please check your corresponding box once you've given the :+1:.
- [x] Code review: @talbs 
- [x] Code review: @andy-armstrong 
- [x] UI strings/error msgs review: @catong (tagging for screenshots if necessary)
- [x] Product review: @explorerleslie 

### Post-review
- [x] Squash commits

### CODE REVIEW

**Comment by cahrens** [comment]
Most of these changes are purely yummy (initializing spinners! expand/collapse indicators! help text that is now accessible because of an info icon! checkmarks to indicate progress!).

There are a couple of things to discuss though. First, the "caret-right" icon is used for 3 different things-- collapse/expand, move on to next step, and just sort of a delineator (with no collapse/expand). For example (in order):

image

image

Secondly, we may to make some elements larger to handle the icon size. For example, see the last incomplete in this screenshot:

image

**Comment by andy-armstrong** [comment]
:+1: Thanks for tackling this clean up (and for noticing it in the first place!)

**Comment by explorerleslie** [comment]
whoa, caret overload and fix the spacing. I agree I think that we should work with @talbs for review and tweaking of this PR before merge.

**Comment by cahrens** [comment]
@talbs I removed the gratuitous usage of "caret-right" on the buttons and non-collapsible headers. The sandbox has been updated.

I think the only issue now is the spacing one that I mentioned. Here are instructions on setting up ora2 on devstack:

https://openedx.atlassian.net/wiki/display/TNL/ORA+FAQ

Let me know if you have issues!

**Comment by explorerleslie** [comment]
holy cow so much better :+1: dependent on fixing the spacing issue.

**Comment by talbs** [comment]
@cahrens and all, I pushed up a ``fixup!`` commit that should address some of the spacing/layout challenges of steps with longer status messages. In short, I focused on:

* allowing room for longer step status labels/headers
* breaking step status/header alignment to block-level earlier - this means the header/status will be shown on new lines earlier in smaller window sizes
* small Sass/CSS clean up along the way - redundant/empty rules

- - -

Let me know if you folks need anything else.

**Comment by cahrens** [comment]
Thanks, @talbs. @explorerleslie, see, no wrapping!

image

**Comment by cahrens** [comment]
BTW, the sandbox is updated with Brian's changes.

**Comment by talbs** [comment]
:+1: from a FED (HTML, Sass/CSS, and Font rendering) perspective.

**Comment by talbs** [comment]
@cahrens and @explorerleslie, FYI - I tried to tackle the toggle heading color issue noted in the grade area with some additional commits. Once this is merged, I may take some extracurricular time to make a quick PR to sync up these headings overall throughout an ORA problem.

**Comment by cahrens** [comment]
@talbs Thanks-- much better!

@andy-armstrong, @explorerleslie, and @catong please take another look. The sandbox is updated now. I'm looking for some more thumbs...

**Comment by andy-armstrong** [comment]
Looks great :+1:

**Comment by catong** [comment]
This looks great! The only thing that keeps sticking out to me, and I don't know if it's in scope for this PR, is the styling of "Your response to the question above:"

oraheading

If not appropriate to change in this PR, then :+1:  from me.

**Comment by cahrens** [comment]
@talbs did your work impact what Carol is seeing at all? Just wondering if I should proceed with squash 'n merge.

**Comment by talbs** [comment]
@catong and @cahrens, no, my changes didn't cause that issue, but I did note it as odd and out of place when working. It would a good follow-up bug/task to address.

**Comment by cahrens** [comment]
Thanks, @talbs. I confirmed the bug exists in master as well.

I will squash 'n merge.

**Pull request merged**
