### PR TITLE
fix travis configuration

### PR DESCRIPTION
**Pull request by muhammad-ammar**
Accidentally merged these branches.

### CODE REVIEW

**Comment by muhammad-ammar** [comment]
@cahrens @macdiesel PTAL. Thanks

**Comment by cahrens** [comment]
What does it mean that you accidentally merged ora-staff-grading? I don't know what this part of the travis configuration does.

FYI, @dianakhuang, @andy-armstrong, and @efischer19.

**Comment by dianakhuang** [comment]
@cahrens I think it was running travis against a merge to master, and the django-1.8 branch, and the ora-staff-grading branch: http://docs.travis-ci.com/user/customizing-the-build/#Building-Specific-Branches

**Comment by cahrens** [comment]
Oh, OK. :+1:

**Comment by muhammad-ammar** [comment]
Thanks @dianakhuang

**Pull request merged**
