### PR TITLE
Update minified js

### PR DESCRIPTION
**Pull request by efischer19**
@cahrens @kevinjkim 

First noticed in https://github.com/edx/edx-ora2/pull/915. I'm not sure how/when this happened, but on master the minified js files are not up-to-date.

This is simply the result of running `make javascript` on master.

### CODE REVIEW

**Comment by efischer19** [comment]
FYI @ssemenova as well.

Idea: could we ought add something to the `.travis.yml` script for this repo to ensure that this doesn't happen on future merges?

**Comment by efischer19** [comment]
@cahrens @ssemenova Any opposition to merging this? It'll make the rebased diff for https://github.com/edx/edx-ora2/pull/915 (changes that don't touch js at all) much cleaner.

**Comment by cahrens** [comment]
Not from me-- but @ssemenova is really the right person to review this given the fact she is actively working on ORA.

**Comment by efischer19** [comment]
Spoke with @ssemenova - since her PR actually touches js files, we're just going to update the minified files there, and then push out an ORA release with both her and @kevinjkim's changes simultaneously. Closing this PR.

**Pull request closed without merging**
