### PR TITLE
[SE-3253] Improve hebrew translation for Assess Peers

### PR DESCRIPTION
**Pull request by pkulkark**
This PR provides an improvement to the Hebrew translation for "Assess Peers".

**Jira Tickets:** [OSPR-5087](https://openedx.atlassian.net/browse/OSPR-5087)

**Merge deadline:** None

**Testing instructions:** TBD

**Reviewers**
- [ ] @clemente
- [ ] edX reviewer[s] TBD

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @pkulkark! I've created [OSPR-5087](https://openedx.atlassian.net/browse/OSPR-5087) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@pkulkark Thank you for your contribution. Typically, all translations are handled through Transifex. Is there a reason why this is not the case here? CC @OmarIthawi

**Comment by OmarIthawi** [comment]
Thanks @natabene for the tag and @pkulkark for the contribution. Same note as Natalia, translation changes should go into the Transifex. Please follow this guide:

 - https://edx.readthedocs.io/projects/edx-developer-guide/en/latest/internationalization/i18n_translators_guide.html

**Comment by OmarIthawi** [comment]
@natabene please assign the ticket for me: https://openedx.atlassian.net/browse/OSPR-5087.

**Comment by natabene** [comment]
Done, @OmarIthawi

**Comment by pkulkark** [comment]
@natabene @OmarIthawi I see. Thanks for letting me know. I will close this one and get it updated in Transifex. Sorry for the noise.

**Comment by edx-webhook** [comment]
@pkulkark Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-ora2&entry.867055334=https://github.com/edx/edx-ora2/pull/1526&entry.1484655318=https://github.com/pkulkark&entry.752974735=2020-10-27+07:01&entry.1917517419=2020-11-09+07:47&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
