### PR TITLE
Re-display assessment tables after tabbing away

### PR DESCRIPTION
**Pull request by OmarIthawi**
Maintain rendered ORA data on course listing dashboard. After tabbbing away there is no need to re-hide the rendered grids or assessment view.

Add code to show the tables if returning the table view if the data has been already been rendered. Tables were only re-displaying when returning from the detailed view of an assessment or from the staff grading view.

This is to address review of #1241 of @bryanlandia

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @OmarIthawi! I've created [OSPR-4008](https://openedx.atlassian.net/browse/OSPR-4008) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by OmarIthawi** [comment]
I've pushed force the branch and opened a new PR: 

cc: @natabene @ormsbee

**Comment by natabene** [comment]
@OmarIthawi Thank you for your contribution. I will queue this for review.

**Comment by OmarIthawi** [comment]
@natabene I think this shouldn't really be queued for review in https://github.com/edx/edx-ora2/pull/1241 since it already passed the review and is ready for merge.

The differences from #1241 is that this one addressed the review comments by:

 - Including more info in the release message
 - Resolving conflicts with `edx:master`

Please see David's comment: https://github.com/edx/edx-ora2/pull/1241#pullrequestreview-279275223 for more info.

cc: @ormsbee

**Comment by natabene** [comment]
@OmarIthawi I see what you mean. In this case @ormsbee should be able to merge after a quick glance and approval.

**Comment by OmarIthawi** [comment]
Thanks Natalia!

**Comment by OmarIthawi** [comment]
Hey @natabene @ormsbee could you please merge this? It's a bit costly to keep it sitting as I have to resolve conflicts every time something's got merged on `master`.

Thank you!

**Comment by natabene** [comment]
@OmarIthawi Sorry about the delay, we will try this week.

**Comment by ormsbee** [comment]
Sorry, I did look over this before. I'll merge now and take care of version bumping separately.

**Comment by edx-webhook** [comment]
@OmarIthawi 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-ora2&entry.867055334=https://github.com/edx/edx-ora2/pull/1327&entry.1484655318=https://github.com/OmarIthawi&entry.752974735=2019-12-31+14:02&entry.1917517419=2020-01-23+17:35&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by OmarIthawi** [comment]
David, Natalia, thank you!

**Pull request merged**
