### PR TITLE
Delete legacy openassessment.css

### PR DESCRIPTION
**Pull request by OmarIthawi**
It's unused and contains an error.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @OmarIthawi! I've created [OSPR-3451](https://openedx.atlassian.net/browse/OSPR-3451) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@OmarIthawi Thank you for your contribution. Please let me know once tests are green.

**Comment by OmarIthawi** [comment]
Thanks @natabene! I have no idea where to start, seems like the ORA2 tests are broken. I'll close this PR.

**Comment by edx-webhook** [comment]
@OmarIthawi Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-ora2&entry.867055334=https://github.com/edx/edx-ora2/pull/1238&entry.1484655318=https://github.com/OmarIthawi&entry.752974735=2019-05-11+16:07&entry.1917517419=2019-05-16+21:53&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
