### PR TITLE
self.STATUS AttributeError

### PR DESCRIPTION
**Pull request by efischer19**
~~This was previously trying to catch the wrong exception type.~~

Nope, had to do with where I check and update `self.STATUS`. In a prior version, I had explicitly added `'staff'` to the class globals in the default values. However, as @andy-armstrong noted in the review process, we were banking on those values never being overridden.

To ensure that `'staff'` was always present, I made it so that we check for it in `start_workflow()`, which I (erroneously) thought was always called when getting a workflow.

Turns out, you can also get an `AssessmentWorkflow` object from the database, in which case the `'staff'` checks were never made, meaning `self.STATUS` never got updated to include `staff`, leading to the `AttributeError`s seen in sandboxes and devstacks.

### CODE REVIEW

**Comment by efischer19** [comment]
Currently working on writing a test to skip `start_workflow()`, to ensure the validity of this proposed fix. All the current tests pass through that method, which is why we never caught this before.

**Comment by efischer19** [comment]
@dianakhuang @andy-armstrong @cahrens - Here's what I think is the cause of the `AttributeError`s that have been showing up.

**Comment by andy-armstrong** [comment]
:+1: Thanks for tracking this down, @efischer19. Can we merge it without a test just to get the feature branch unlocked? Or are you close to having a test?

**Comment by dianakhuang** [comment]
:+1: from me.

**Comment by efischer19** [comment]
I'm not super close to getting a test written (creating a workflow without actually calling `start_workflow` is tricky), but I'd be more than happy to merge without if we can confirm this actually fixes things.

**Pull request merged**
