### PR TITLE
Added beta tester functionality.

### PR DESCRIPTION
**Pull request by waheedahmed**
[TNL-1736] (https://openedx.atlassian.net/browse/TNL-1736)

Should be released with this fix from platform: https://github.com/edx/edx-platform/pull/7422

### CODE REVIEW

**Comment by waheedahmed** [comment]
@symbolist @muzaffaryousaf @adampalay @muhammad-ammar  Please review this.

**Comment by adampalay** [comment]
looks good, but needs tests

**Comment by waheedahmed** [comment]
@adampalay Added couple of unit tests.

**Comment by adampalay** [comment]
:+1:

**Comment by symbolist** [comment]
:+1:

**Comment by adampalay** [comment]
@symbolist will there be an updated ora hash in the next release, or should @waheedahmed make one?

**Pull request merged**
